[build-system]
requires = ["setuptools>=61.0"]
build-backend= "setuptools.build_meta"

[project]
name = "ArrayGen"
version = "1.3.3"
description = "An array generation and visulisation tool."
authors = [
    { name = "Aarin J"}
]
dependencies = [
    "numpy>=1.22.0",
    "matplotlib>=3.5.0",
    "ipywidgets",
    "sympy",
    "pillow",
    "plotly",
]
requires-python = ">=3.12"
license = { text = "MIT"}
readme = "README.md"

classifiers = [
    "Intended Audience :: Education",
    "Topic :: Education",
    "Programming language :: Python :: 3.12"
]

[project.urls]
Homepage = "https://github.com/Titutiger/Arraygen"
Documentation = "https://github.com/Titutiger/Arraygen"
Repository = "https://github.com/Titutiger/Arraygen"

